branch-defaults:
  default:
    environment: alert-triage-env
    group_suffix: null
global:
  application_name: alert-triage-ai
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
